### PR TITLE
MechComp

### PR DESCRIPTION
**Pull request by MechComp**
CSS update on licence stats

### CODE REVIEW

**Comment by MechComp** [comment]
Hi,

in the last version of the plugin I have changed the way how orders look like and behave.

The old approach was adding the license info as order meta and then displaying them. This didn't work well when there were more licenses than one or more than one licensed product. Also, the plugin never tried to check if there are any existing licenses for current order. So when someone changed the order status from completed to on-hold and back, plugin created new licenses for the user.
I have narrowed down the number of metadata to just license key and type. Everything else when added to the order was relevant just at the time of license being created. So when there was a change in license afterwards, it wasn't changed in the order again. This data can be found then in the license record itself.

There are also two new options:
1. In WooCommerce, you can disable the automatic Downloads expiration. This is for the reason that if you don't want downloads behave the same way as license. Example: License for life, downloads for a year. Before when I wanted to have this behavior, I had to set product as subscription and set expiration to 0.
2. In some recent version, there was created new feature to allow users to remove domains in "My licenses". As in my case the license is checked only manually on button activation, when customer removes the domain in their account they can use it on multiple domains without corresponding number of licenses. If the licensed plugin checks the license regularly then it will find out. So for this reason there is an option for it.

**Comment by MechComp** [comment]
Commit 5a26db6 is about the appearance of licences - added item reference and the info was too wide, it did two rows so the look was altered a bit.

**Comment by MechComp** [comment]
Commit 4964669 makes the item reference work. When the SQL select does not include item reference, the customer is able to activate the license for whatever product he wants. Thus the feature is not working.

**Comment by michelve** [comment]
Thank you @MechComp - i have allowed the pull request

**Pull request merged**
